---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: simonyas/my-image:2
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
  labels:
    svc: echoserver
spec:
  ports:
  - name: echoserver-http
    port: 80
    targetPort: 5005
    protocol: TCP
  selector:
    app: echoserver
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # this will rewrite request under / + second capture group
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: simonots.site
    http:
      paths:
        # this will serve all paths under /my-nginx and capture groups for regex annotations
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: echoserver
            port:
              number: 80
  tls:
  - hosts:
    - simonots.site
    secretName: externaluicerts
---
